# Generated by Django 4.1.5 on 2023-07-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_blockedsite_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedsite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.DeleteModel(
            name='BlockedSite',
        ),
    ]
