# Generated by Django 4.1.5 on 2023-07-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_blockedsite_user_delete_alarm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sending_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sending_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.JSONField(default=1, verbose_name='message data'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
