# Generated by Django 4.1.5 on 2023-07-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_template_user_remove_task_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Schedule Date'),
        ),
    ]
