# Generated by Django 4.2.3 on 2023-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_task_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='is sent'),
        ),
    ]
